version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Diff Changes
          command: echo "We'll eventually figure out what changes took place and only build/deploy those"
  
  selftest:
    docker:
      - image: circle/python:3.7

    steps:
      - run:
          name: Selftests
          command:
            mkdir -p agents/selftest
            cd agents/selftest
            python3 ../agents.py

      - store_artifacts:
          path: agents/selftest/
          destination: agents/

  deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - run: |
          echo "We'll figure out deploy steps eventually"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - selftest:
          requires:
            - build
      - deploy:
          requires:
            - selftest
          filters:
            branches:
              only: master
